version: '2.3'
services:
  supabase_metrics:
    image: docker.elastic.co/observability/stream:v0.22.0
    hostname: supabase_metrics
    ports:
      - "8080"
    volumes:
      - ./config.yml:/config.yml:ro
    environment:
      PORT: '8080'
    command:
      - http-server
      - --addr=:8080
      - --config=/config.yml
